# Generated by Django 4.0 on 2023-01-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='profile_tags', to='blog.Tag'),
        ),
    ]
